import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,MapPin,ShoppingBag,Heart,Star,Clock,ChevronRight,Plus,Minus,ArrowLeft,Menu,User,ShieldCheck,Truck,Receipt,LogOut,X,CheckCircle2} from 'lucide-react';
import './styles.css';

const restaurants=[
 {id:1,name:'Spice Route',cuisine:'North Indian • Biryani',rating:4.7,time:'25–30 min',price:'₹₹',img:'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80',offer:'50% OFF'},
 {id:2,name:'Burger District',cuisine:'Burgers • Fast Food',rating:4.5,time:'20–25 min',price:'₹₹',img:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80',offer:'20% OFF'},
 {id:3,name:'Pizza Atelier',cuisine:'Pizza • Italian',rating:4.6,time:'30–35 min',price:'₹₹₹',img:'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=80',offer:'FREE DELIVERY'},
 {id:4,name:'Wok & Bowl',cuisine:'Chinese • Asian',rating:4.4,time:'25–30 min',price:'₹₹',img:'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=900&q=80',offer:'30% OFF'},
 {id:5,name:'Green Theory',cuisine:'Healthy • Salads',rating:4.8,time:'20–25 min',price:'₹₹₹',img:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80',offer:'15% OFF'},
 {id:6,name:'Sweet Crumbs',cuisine:'Desserts • Bakery',rating:4.6,time:'15–20 min',price:'₹',img:'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=900&q=80',offer:'BUY 1 GET 1'}
];
const foods=[
 {id:101,name:'Chicken Biryani',desc:'Aromatic basmati rice, tender chicken and whole spices.',price:249,img:'https://images.unsplash.com/photo-1563379091339-03246963d96c?auto=format&fit=crop&w=600&q=80'},
 {id:102,name:'Butter Chicken',desc:'Creamy tomato gravy with smoky tandoori chicken.',price:289,img:'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80'},
 {id:103,name:'Margherita Pizza',desc:'San Marzano tomato, mozzarella and fresh basil.',price:249,img:'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=600&q=80'},
 {id:104,name:'Classic Cheeseburger',desc:'Juicy patty, cheddar, lettuce and house sauce.',price:199,img:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80'},
 {id:105,name:'Paneer Tikka',desc:'Charred paneer with peppers and mint chutney.',price:219,img:'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=600&q=80'},
 {id:106,name:'Mango Cheesecake',desc:'Silky cheesecake topped with ripe mango.',price:179,img:'https://images.unsplash.com/photo-1541783245831-57d6fb0926d3?auto=format&fit=crop&w=600&q=80'}
];
const categories=['🍛 Indian','🍕 Pizza','🍔 Burgers','🍜 Chinese','🥗 Healthy','🍰 Desserts','☕ Beverages'];

function Header({cartCount,onCart,onProfile}){return <header className="header"><div className="container nav"><button className="brand" onClick={()=>location.hash='home'}><span className="brand-mark">F</span><span>Food <b>Express</b></span></button><div className="location"><MapPin size={18}/><div><small>Deliver to</small><strong>Home · Select location</strong></div></div><div className="search"><Search size={19}/><input placeholder="Search restaurants or dishes" onKeyDown={e=>{if(e.key==='Enter') location.hash='restaurants'}}/></div><button className="navlink hide-mobile" onClick={()=>location.hash='restaurants'}>Restaurants</button><button className="icon-btn" onClick={onProfile}><User size={20}/></button><button className="cart-btn" onClick={onCart}><ShoppingBag size={19}/><span>Cart</span>{cartCount>0&&<em>{cartCount}</em>}</button></div></header>}
function Hero(){return <section className="hero"><div className="container hero-grid"><div><div className="eyebrow">FAST • FRESH • AT YOUR DOOR</div><h1>Good food.<br/><span>Fast delivery.</span></h1><p>Discover the best restaurants around you, order in seconds, and track every bite from kitchen to doorstep.</p><div className="hero-search"><MapPin size={20}/><span>Deliver to</span><button onClick={()=>location.hash='restaurants'}>Explore food <ChevronRight size={18}/></button></div><div className="trust"><ShieldCheck size={17}/> Live order tracking <span/> <Clock size={17}/> 25–35 min average</div></div><div className="hero-art"><div className="hero-card"><span>🔥 Trending today</span><strong>Butter Chicken</strong><small>Spice Route · ⭐ 4.8</small><b>₹289</b></div></div></div></section>}
function CategoryStrip(){return <section className="container section"><div className="section-head"><div><small>WHAT ARE YOU CRAVING?</small><h2>Explore by category</h2></div><ChevronRight/></div><div className="categories">{categories.map(c=><button key={c} onClick={()=>location.hash='restaurants'}>{c}</button>)}</div></section>}
function RestaurantCard({r}){return <article className="restaurant-card" onClick={()=>location.hash='restaurant'}><div className="image-wrap"><img src={r.img}/><span>{r.offer}</span><button onClick={e=>e.stopPropagation()}><Heart size={18}/></button></div><div className="card-body"><div className="row"><h3>{r.name}</h3><b className="rating"><Star size={14} fill="currentColor"/> {r.rating}</b></div><p>{r.cuisine}</p><div className="meta"><span><Clock size={14}/> {r.time}</span><span>{r.price}</span></div></div></article>}
function Home({onAdd}){return <><Hero/><CategoryStrip/><section className="container section"><div className="section-head"><div><small>NEAR YOU</small><h2>Popular restaurants</h2></div><button className="text-btn" onClick={()=>location.hash='restaurants'}>View all <ChevronRight size={16}/></button></div><div className="restaurant-grid">{restaurants.slice(0,4).map(r=><RestaurantCard key={r.id} r={r}/>)}</div></section><section className="container promo"><div><small>WELCOME TO FOOD EXPRESS</small><h2>Get 50% off your first order</h2><p>Use code <b>WELCOME50</b> at checkout. Delicious food is just a few clicks away.</p><button onClick={()=>location.hash='restaurants'}>Start ordering <ChevronRight size={18}/></button></div><div className="promo-orb">50<span>%</span></div></section><section className="container section"><div className="section-head"><div><small>TOP PICKS</small><h2>Popular right now</h2></div></div><div className="food-grid">{foods.map(f=><FoodCard key={f.id} food={f} onAdd={onAdd}/>)}</div></section></>}
function FoodCard({food,onAdd}){return <article className="food-card"><img src={food.img}/><div><h3>{food.name}</h3><p>{food.desc}</p><div className="row"><strong>₹{food.price}</strong><button className="add" onClick={()=>onAdd(food)}>+ Add</button></div></div></article>}
function RestaurantsPage({onAdd}){return <main className="container page"><div className="breadcrumb">Home / Restaurants</div><div className="page-title"><div><small>DISCOVER</small><h1>Restaurants near you</h1><p>Fresh food from highly rated local kitchens.</p></div><button className="filter">Filter & Sort</button></div><div className="chips">{['Recommended','Fast delivery','Rating 4.5+','Pure veg','Offers','₹ Budget'].map(x=><button key={x}>{x}</button>)}</div><div className="restaurant-grid">{restaurants.map(r=><RestaurantCard key={r.id} r={r}/>)}</div></main>}
function RestaurantPage({onAdd}){return <main className="container page"><button className="back" onClick={()=>location.hash='restaurants'}><ArrowLeft size={17}/> Restaurants</button><section className="restaurant-hero"><img src={restaurants[0].img}/><div><span className="open">OPEN NOW</span><h1>Spice Route</h1><p>North Indian · Biryani · Mughlai</p><div className="restaurant-stats"><b>★ 4.7</b><span>2.4k ratings</span><span>25–30 min</span><span>₹300 for two</span></div><p className="desc">Comforting Indian classics, fragrant biryanis and rich curries made fresh to order.</p></div></section><nav className="menu-tabs"><b>Recommended</b><span>Starters</span><span>Biryani</span><span>Main Course</span><span>Desserts</span></nav><h2 className="menu-heading">Recommended</h2><div className="menu-list">{foods.slice(0,4).map(f=><FoodCard key={f.id} food={f} onAdd={onAdd}/>)}</div></main>}
function Cart({cart,onClose,onCheckout,onUpdate}){const total=cart.reduce((s,x)=>s+x.price*x.qty,0);return <aside className="drawer"><div className="drawer-head"><div><small>YOUR ORDER</small><h2>Cart</h2></div><button onClick={onClose}><X/></button></div>{cart.length===0?<div className="empty"><ShoppingBag size={42}/><h3>Your cart is empty</h3><p>Add something delicious to get started.</p></div>:<><div className="cart-items">{cart.map(x=><div className="cart-item" key={x.id}><img src={x.img}/><div><h3>{x.name}</h3><span>₹{x.price}</span><div className="qty"><button onClick={()=>onUpdate(x.id,-1)}><Minus size={13}/></button><b>{x.qty}</b><button onClick={()=>onUpdate(x.id,1)}><Plus size={13}/></button></div></div></div>)}</div><div className="bill"><div><span>Item total</span><b>₹{total}</b></div><div><span>Delivery fee</span><b>₹30</b></div><div><span>Taxes</span><b>₹{Math.round(total*.05)}</b></div><div className="discount"><span>WELCOME50</span><b>-₹{Math.min(50,total)}</b></div><hr/><div className="grand"><span>Total</span><b>₹{total+30+Math.round(total*.05)-Math.min(50,total)}</b></div></div><button className="checkout" onClick={onCheckout}>Proceed to checkout <ChevronRight size={18}/></button></>}</aside>}
function Checkout({cart,onBack,onDone}){const subtotal=cart.reduce((s,x)=>s+x.price*x.qty,0),total=subtotal+30+Math.round(subtotal*.05)-Math.min(50,subtotal);const [payment,setPayment]=useState('UPI');return <main className="container page checkout-page"><button className="back" onClick={onBack}><ArrowLeft size={17}/> Back to cart</button><div className="checkout-grid"><div><div className="steps"><b>1 Cart</b><span>→</span><b>2 Address</b><span>→</span><b>3 Payment</b></div><section className="checkout-card"><div className="section-head"><div><small>DELIVERY</small><h2>Delivery address</h2></div><button className="text-btn">Change</button></div><div className="address active"><MapPin/><div><b>Home</b><p>123 Main Street, Baddi, Himachal Pradesh</p></div><CheckCircle2/></div></section><section className="checkout-card"><small>PAYMENT</small><h2>Choose payment method</h2>{['UPI','Credit / Debit Card','Cash on Delivery'].map(p=><button className={'payment '+(payment===p?'selected':'')} key={p} onClick={()=>setPayment(p)}><span>{p}</span>{payment===p&&<CheckCircle2/>}</button>)}</section></div><section className="checkout-card summary"><small>ORDER SUMMARY</small><h2>Spice Route</h2>{cart.map(x=><div className="summary-row" key={x.id}><span>{x.qty} × {x.name}</span><b>₹{x.qty*x.price}</b></div>)}<hr/><div className="summary-row"><span>Delivery</span><b>₹30</b></div><div className="summary-row"><span>Taxes</span><b>₹{Math.round(subtotal*.05)}</b></div><div className="summary-row discount"><span>WELCOME50</span><b>-₹{Math.min(50,subtotal)}</b></div><div className="grand"><span>Total</span><b>₹{total}</b></div><button className="checkout" onClick={onDone}>Place order · ₹{total}</button></section></div></main>}
function Profile(){return <main className="container page profile-page"><div className="profile-head"><div className="avatar">AS</div><div><small>MY ACCOUNT</small><h1>Welcome back</h1><p>Manage your orders, addresses and preferences.</p></div></div><div className="profile-grid">{[['Orders','Track current and past orders',Receipt],['Addresses','Manage your delivery locations',MapPin],['Favorites','Your saved restaurants and dishes',Heart],['Payments','Saved payment methods',ShieldCheck]].map(([a,b,I])=><button className="profile-card" key={a}><I/><div><h3>{a}</h3><p>{b}</p></div><ChevronRight/></button>)}</div></main>}
function Success({onHome}){return <main className="success-page"><div className="success-card"><div className="success-icon"><CheckCircle2 size={54}/></div><small>ORDER CONFIRMED</small><h1>You're all set! 🎉</h1><p>Your order from <b>Spice Route</b> has been confirmed.</p><div className="eta"><Clock/><div><small>ESTIMATED DELIVERY</small><strong>25–30 minutes</strong></div></div><div className="tracking"><span className="done"/><span className="done"/><span/><span/><div><b>Order confirmed</b><small>Restaurant is preparing your food</small></div></div><button className="checkout" onClick={onHome}>Back to home</button></div></main>}
function App(){const [cart,setCart]=useState([]);const [drawer,setDrawer]=useState(false);const [view,setView]=useState(location.hash.replace('#','')||'home');const [ordered,setOrdered]=useState(false);React.useEffect(()=>{const fn=()=>setView(location.hash.replace('#','')||'home');addEventListener('hashchange',fn);return()=>removeEventListener('hashchange',fn)},[]);const add=food=>{setCart(c=>{const e=c.find(x=>x.id===food.id);return e?c.map(x=>x.id===food.id?{...x,qty:x.qty+1}:x):[...c,{...food,qty:1}]});setDrawer(true)};const update=(id,d)=>setCart(c=>c.map(x=>x.id===id?{...x,qty:x.qty+d}:x).filter(x=>x.qty>0));const content=ordered?<Success onHome={()=>{setOrdered(false);location.hash='home'}}/>:view==='restaurants'?<RestaurantsPage onAdd={add}/>:view==='restaurant'?<RestaurantPage onAdd={add}/>:view==='checkout'?<Checkout cart={cart} onBack={()=>{location.hash='home';setDrawer(true)}} onDone={()=>{setDrawer(false);setOrdered(true)}}/>:view==='profile'?<Profile/>:<Home onAdd={add}/>;return <><Header cartCount={cart.reduce((s,x)=>s+x.qty,0)} onCart={()=>setDrawer(true)} onProfile={()=>location.hash='profile'}/>{content}{!ordered&&<footer><div className="container footer-grid"><div><div className="brand"><span className="brand-mark">F</span><span>Food <b>Express</b></span></div><p>Good food. Fast delivery.</p></div><div><b>Company</b><span>About</span><span>Careers</span><span>Partner with us</span></div><div><b>Support</b><span>Help Center</span><span>Terms</span><span>Privacy</span></div></div></footer>}{drawer&&<><div className="overlay" onClick={()=>setDrawer(false)}/><Cart cart={cart} onClose={()=>setDrawer(false)} onUpdate={update} onCheckout={()=>{setDrawer(false);location.hash='checkout'}}/></>}</>}

createRoot(document.getElementById('root')).render(<App/>);